server:
  port: 8080
security:
  basic:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://35.183.1.239:8761/eureka/
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=Oracle
  rabbitmq:
    addresses: amqp://xromjjrg:0TPRFYCAXJ8I4rUym7KgUEWgHnK6yopu@sassy-wombat.rmq.cloudamqp.com/
    host: sassy-wombat.rmq.cloudamqp.com
    port: 5672
    username: xromjjrg 
    password: 0TPRFYCAXJ8I4rUym7KgUEWgHnK6yopu 